#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-kotlin
Version  : 1
Release  : 1
URL      : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin/1.1.51/kotlin-sam-with-receiver-compiler-plugin-1.1.51.jar
Source0  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin/1.1.51/kotlin-sam-with-receiver-compiler-plugin-1.1.51.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/org/gradle/gradle-kotlin-dsl-tooling-builders/0.12.3/gradle-kotlin-dsl-tooling-builders-0.12.3.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/gradle/gradle-kotlin-dsl-tooling-builders/0.12.3/gradle-kotlin-dsl-tooling-builders-0.12.3.pom
Source3  : https://repo.gradle.org/gradle/libs-releases/org/gradle/gradle-kotlin-dsl-tooling-models/0.12.3/gradle-kotlin-dsl-tooling-models-0.12.3.jar
Source4  : https://repo.gradle.org/gradle/libs-releases/org/gradle/gradle-kotlin-dsl-tooling-models/0.12.3/gradle-kotlin-dsl-tooling-models-0.12.3.pom
Source5  : https://repo.gradle.org/gradle/libs-releases/org/gradle/gradle-kotlin-dsl/0.12.3/gradle-kotlin-dsl-0.12.3.jar
Source6  : https://repo.gradle.org/gradle/libs-releases/org/gradle/gradle-kotlin-dsl/0.12.3/gradle-kotlin-dsl-0.12.3.pom
Source7  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.51/kotlin-compiler-embeddable-1.1.51.jar
Source8  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.51/kotlin-compiler-embeddable-1.1.51.pom
Source9  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-project/1.1.51/kotlin-project-1.1.51.pom
Source10  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-reflect/1.1.51/kotlin-reflect-1.1.51.jar
Source11  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-reflect/1.1.51/kotlin-reflect-1.1.51.pom
Source12  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin/1.1.51/kotlin-sam-with-receiver-compiler-plugin-1.1.51.pom
Source13  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-stdlib/1.1.51/kotlin-stdlib-1.1.51.jar
Source14  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlin/kotlin-stdlib/1.1.51/kotlin-stdlib-1.1.51.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-kotlin-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-kotlin package.
Group: Data

%description data
data components for the mvn-kotlin package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin/1.1.51
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin/1.1.51/kotlin-sam-with-receiver-compiler-plugin-1.1.51.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-builders/0.12.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-builders/0.12.3/gradle-kotlin-dsl-tooling-builders-0.12.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-builders/0.12.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-builders/0.12.3/gradle-kotlin-dsl-tooling-builders-0.12.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-models/0.12.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-models/0.12.3/gradle-kotlin-dsl-tooling-models-0.12.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-models/0.12.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-models/0.12.3/gradle-kotlin-dsl-tooling-models-0.12.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl/0.12.3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl/0.12.3/gradle-kotlin-dsl-0.12.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl/0.12.3
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl/0.12.3/gradle-kotlin-dsl-0.12.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.51
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.51/kotlin-compiler-embeddable-1.1.51.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.51
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.51/kotlin-compiler-embeddable-1.1.51.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-project/1.1.51
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-project/1.1.51/kotlin-project-1.1.51.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.1.51
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.1.51/kotlin-reflect-1.1.51.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.1.51
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.1.51/kotlin-reflect-1.1.51.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin/1.1.51
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin/1.1.51/kotlin-sam-with-receiver-compiler-plugin-1.1.51.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.1.51
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.1.51/kotlin-stdlib-1.1.51.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.1.51
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.1.51/kotlin-stdlib-1.1.51.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-builders/0.12.3/gradle-kotlin-dsl-tooling-builders-0.12.3.jar
/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-builders/0.12.3/gradle-kotlin-dsl-tooling-builders-0.12.3.pom
/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-models/0.12.3/gradle-kotlin-dsl-tooling-models-0.12.3.jar
/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl-tooling-models/0.12.3/gradle-kotlin-dsl-tooling-models-0.12.3.pom
/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl/0.12.3/gradle-kotlin-dsl-0.12.3.jar
/usr/share/java/.m2/repository/org/gradle/gradle-kotlin-dsl/0.12.3/gradle-kotlin-dsl-0.12.3.pom
/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.51/kotlin-compiler-embeddable-1.1.51.jar
/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.51/kotlin-compiler-embeddable-1.1.51.pom
/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-project/1.1.51/kotlin-project-1.1.51.pom
/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.1.51/kotlin-reflect-1.1.51.jar
/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.1.51/kotlin-reflect-1.1.51.pom
/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin/1.1.51/kotlin-sam-with-receiver-compiler-plugin-1.1.51.jar
/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin/1.1.51/kotlin-sam-with-receiver-compiler-plugin-1.1.51.pom
/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.1.51/kotlin-stdlib-1.1.51.jar
/usr/share/java/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.1.51/kotlin-stdlib-1.1.51.pom
